# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170622_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='status',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Devis',
        ),
    ]
