# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_project_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id_status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DEVEC', 'Devis en cours'), ('FACEC', 'Facture en cours'), ('DVALI', 'Valid\xe9'), ('FPAYE', 'Pay\xe9')], default='yolo', max_length=150),
            preserve_default=False,
        ),
    ]
