# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170703_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Devis en Cours', 'Devis en cours'), ('Facture en Cours', 'Facture en cours'), ('DVALI', 'Valid\xe9'), ('Facture Pay\xe9e', 'Pay\xe9')], max_length=150),
        ),
    ]
