# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170706_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_acceptance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_refusal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Devis en Cours', 'Devis en cours'), ('Facture en Cours', 'Facture en cours'), ('Devis Perdu', 'Perdu'), ('Facture Pay\xe9e', 'Pay\xe9')], max_length=150),
        ),
    ]
