# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170706_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
