# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170710_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
